**`import librarys`**

In [1]:
#import library pandan
#syntax for import (import library name as pd)
import pandas as pd

**load** **dataset**

In [2]:
#read data from google colab
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/CRIME-DATA-ANALYSIS-COMPLA.xlsx")

**#Undrestanding Dataset**

## undrestanding first 5 rows uding heading fuction

In [3]:
##read

In [4]:
data.head()

,Crime_ID,Crime_Date,Crime_Type,District,Victim_Gender,Case_Status,Severity_Level
0,CRM00054,2025-07-11 00:00:00,Theft,Karan,Male,Closed,NaN
1,CRM00290,2025-02-26 00:00:00,Burglary,NaN,Male,Closed,Medium
2,CRM00143,2026-05-26 00:00:00,Theft,Wadajir,Female,NaN,Medium
3,CRM00198,2025-02-17 00:00:00,Assault,Wadajir,Male,Open,High
4,CRM00244,2026-02-27 00:00:00,Assault,Hodan,Female,Under Investigation,High

## undrestanding last 5 rows uding heading fuction

---

In [5]:
data.tail()

,Crime_ID,Crime_Date,Crime_Type,District,Victim_Gender,Case_Status,Severity_Level
295,CRM00052,2025-02-03 00:00:00,Robbery,Wadajir,Female,Under Investigation,NaN
296,CRM00085,2025-12-09 00:00:00,NaN,Hodan,Male,Open,Medium
297,CRM00057,2025-01-24 00:00:00,Traffic Offense,Waberi,Female,Under Investigation,Low
298,CRM00023,2025-02-23 00:00:00,Robbery,Wadajir,Male,Closed,High
299,CRM00077,2026-05-01 00:00:00,Traffic Offense,Hodan,Male,Closed,NaN

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Crime_ID        285 non-null    object
 1   Crime_Date      282 non-null    object
 2   Crime_Type      284 non-null    object
 3   District        284 non-null    object
 4   Victim_Gender   284 non-null    object
 5   Case_Status     283 non-null    object
 6   Severity_Level  280 non-null    object
dtypes: object(7)
memory usage: 16.5+ KB

In [7]:
data.sample(5)

,Crime_ID,Crime_Date,Crime_Type,District,Victim_Gender,Case_Status,Severity_Level
211,CRM00071,2026-07-20 00:00:00,Traffic Offense,Daynile,Male,Closed,Low
143,CRM00146,2025-07-12 00:00:00,Assault,Waberi,Female,Open,High
200,CRM00148,2025-07-12 00:00:00,Theft,Wadajir,Unknown,Closed,Medium
199,CRM00188,2026-02-02 00:00:00,Assault,Wadajir,Female,Open,High
285,CRM00055,2025-09-08 00:00:00,Traffic Offense,Waberi,Male,Under Investigation,Low

# **show the display data shape**

In [8]:
data.shape

(300, 7)

this dataset 24 rows and 9 column

In [9]:
data.columns

Index(['Crime_ID', 'Crime_Date', 'Crime_Type', 'District', 'Victim_Gender',
       'Case_Status', 'Severity_Level'],
      dtype='object')

## Display dta types my dtaset using propery using (datatype)

In [10]:
data.dtypes

Crime_ID          object
Crime_Date        object
Crime_Type        object
District          object
Victim_Gender     object
Case_Status       object
Severity_Level    object
dtype: object

## summary of dataframe

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Crime_ID        285 non-null    object
 1   Crime_Date      282 non-null    object
 2   Crime_Type      284 non-null    object
 3   District        284 non-null    object
 4   Victim_Gender   284 non-null    object
 5   Case_Status     283 non-null    object
 6   Severity_Level  280 non-null    object
dtypes: object(7)
memory usage: 16.5+ KB

## display the describe of statistics using describe fuction

In [12]:
data.describe(include="all")

,Crime_ID,Crime_Date,Crime_Type,District,Victim_Gender,Case_Status,Severity_Level
count,285,282,284,284,284,283,280
unique,277,228,8,7,4,6,5
top,CRM00013,2025-09-01 00:00:00,Theft,Hodan,Male,Closed,Medium
freq,2,4,82,74,162,115,150

In [13]:
data.describe()

,Crime_ID,Crime_Date,Crime_Type,District,Victim_Gender,Case_Status,Severity_Level
count,285,282,284,284,284,283,280
unique,277,228,8,7,4,6,5
top,CRM00013,2025-09-01 00:00:00,Theft,Hodan,Male,Closed,Medium
freq,2,4,82,74,162,115,150

In [14]:
data.describe(include='object')

,Crime_ID,Crime_Date,Crime_Type,District,Victim_Gender,Case_Status,Severity_Level
count,285,282,284,284,284,283,280
unique,277,228,8,7,4,6,5
top,CRM00013,2025-09-01 00:00:00,Theft,Hodan,Male,Closed,Medium
freq,2,4,82,74,162,115,150