In [2]:
import pandas as pd

In [3]:
# loading data
data=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/CRIME-DATA-ANALYSIS-COMPLA.xlsx")

In [4]:
data.head()

,Crime_ID,Crime_Date,Crime_Type,District,Victim_Gender,Case_Status,Severity_Level
0,CRM00054,2025-07-11 00:00:00,Theft,Karan,Male,Closed,NaN
1,CRM00290,2025-02-26 00:00:00,Burglary,NaN,Male,Closed,Medium
2,CRM00143,2026-05-26 00:00:00,Theft,Wadajir,Female,NaN,Medium
3,CRM00198,2025-02-17 00:00:00,Assault,Wadajir,Male,Open,High
4,CRM00244,2026-02-27 00:00:00,Assault,Hodan,Female,Under Investigation,High


##Renaming

In [5]:
data = data.rename(columns={"Crime_ID": "Crimid"})

In [6]:
data.head()

,Crimid,Crime_Date,Crime_Type,District,Victim_Gender,Case_Status,Severity_Level
0,CRM00054,2025-07-11 00:00:00,Theft,Karan,Male,Closed,NaN
1,CRM00290,2025-02-26 00:00:00,Burglary,NaN,Male,Closed,Medium
2,CRM00143,2026-05-26 00:00:00,Theft,Wadajir,Female,NaN,Medium
3,CRM00198,2025-02-17 00:00:00,Assault,Wadajir,Male,Open,High
4,CRM00244,2026-02-27 00:00:00,Assault,Hodan,Female,Under Investigation,High

In [7]:
data["District"].value_counts()

District
Hodan      74
Wadajir    62
Yaqshid    42
Daynile    39
Karan      33
Waberi     33
-           1
Name: count, dtype: int64

In [13]:
data["District"] = data["District"].replace("hodan", "Hodan")

In [10]:
data["District"].value_counts()

District
Hodan      74
Wadajir    62
Yaqshid    42
Daynile    39
Karan      33
Waberi     33
-           1
Name: count, dtype: int64

In [11]:
data["Crime_Type"].value_counts()

Crime_Type
Theft              82
Fraud              56
Assault            55
Robbery            43
Traffic Offense    28
Burglary           18
-                   1
THEFT               1
Name: count, dtype: int64

In [12]:
data["Victim_Gender"] = data["Victim_Gender"].replace({
    "male": "Male",
    "female": "Female"
})

In [14]:
data["Victim_Gender"].value_counts()

Victim_Gender
Male       162
Female      92
Unknown     29
MALE         1
Name: count, dtype: int64

In [15]:
data["Case_Status"] = data["Case_Status"].replace({
    "open": "Open",
    "closed": "Closed",
    "under investigation": "Under Investigation"
})

In [16]:
data["Case_Status"].value_counts()

Case_Status
Closed                 116
Under Investigation     74
Open                    66
Referred                27
Name: count, dtype: int64

##numerical replacment

In [19]:
data["Severity_Level"] = data["Severity_Level"].replace({
    "Low": 1,
    "Medium": 2,
    "High": 3
})

In [20]:
data["Severity_Level"].value_counts()

Severity_Level
2         150
3          98
1          28
MEDIUM      3
medium      1
Name: count, dtype: int64

In [21]:
data.dtypes

Crimid            object
Crime_Date        object
Crime_Type        object
District          object
Victim_Gender     object
Case_Status       object
Severity_Level    object
dtype: object

##Changing datatypes

In [22]:
data["Crime_Date"] = pd.to_datetime(data["Crime_Date"], errors="coerce")

In [24]:
data["Crime_Date"] = pd.to_datetime(
    data["Crime_Date"],
    errors="coerce"
)